name: mumin
description: "A new Flutter project."
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# of the product and file versions while build-number is used as the build suffix.
version: 1.8.1+21

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  geolocator: ^14.0.1
  flutter_compass: ^0.8.1
  permission_handler: ^12.0.1
  intl: ^0.20.2
  gap: ^3.0.1
  get: ^5.0.0-release-candidate-9.2.1
  geocoding: ^4.0.0
  webview_flutter: ^4.10.0
  fluentui_system_icons: ^1.1.273
  toastification: ^3.0.3
  shared_preferences: ^2.5.2
  google_fonts: ^6.2.1
  just_audio: ^0.10.5
  just_audio_background: ^0.0.1-beta.15
  http: ^1.3.0
  hive_flutter: ^1.1.0
  hive: ^2.2.3
  vector_math: ^2.1.4
  record: ^6.1.2
  path_provider: ^2.1.5
  path: ^1.9.1
  share_plus: ^12.0.1
  syncfusion_flutter_pdfviewer: ^32.1.19
  dio: ^5.8.0+1
  flutter_native_splash: ^2.4.4
  flutter_svg: ^2.0.17
  flutter_animate: ^4.5.2
  internet_connection_checker_plus: ^2.7.0
  flutter_launcher_icons: ^0.14.3
  package_info_plus: ^9.0.0
  fluttertoast: ^9.0.0
  clipboard: ^3.0.8
  awesome_notifications: ^0.10.1
  icons_launcher: ^3.0.0
  url_launcher: ^6.3.1
  wakelock_plus: ^1.2.10
  go_router: ^17.0.1
  font_awesome_flutter: ^10.12.0
  vibration: ^3.1.5
  hijri: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icons/
    - assets/images/
    - assets/quran/
    - assets/calender_data/
  fonts:
    - family: IndopakNastaleeq
      fonts:
        - asset: assets/fonts/Quran/IndopakNastaleeq_font.ttf
    - family: surah-name-v1
      fonts:
        - asset: assets/fonts/Quran/surah-name-v1.ttf

flutter_native_splash:
  color: "#121212"
  image: assets/icons/app_icon.png
  color_dark: "#121212"
  image_dark: assets/icons/app_icon.png

  android_12:
    image: assets/icons/app_icon.png
    icon_background_color: "#121212"
    image_dark: assets/icons/app_icon.png
    icon_background_color_dark: "#121212"

  web: false

icons_launcher:
  image_path: "assets/icons/app_icon.png"
  platforms:
    android:
      enable: true
    ios:
      enable: true
